# Generated by Django 3.2.9 on 2021-12-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='OrderItem',
            old_name='service_option',
            new_name='service',
        ),
    ]
