# Generated by Django 3.2.9 on 2021-12-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211214_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order_item_list', to='orders.OrderItem'),
        ),
    ]
