# Generated by Django 3.2.9 on 2021-12-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_active',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_reviewable',
            field=models.BooleanField(default=False),
        ),
    ]
