# Generated by Django 3.2.9 on 2021-12-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(choices=[('9:00', '9:00 a.m.'), ('10:00', '10:00 a.m.'), ('11:00', '11:00 a.m.'), ('12:00', '12:00 p.m.'), ('13:00', '1:00 p.m.'), ('14:00', '2:00 p.m.'), ('15:00', '3:00 p.m.'), ('16:00', '4:00 p.m.'), ('17:00', '5:00 p.m.'), ('18:00', '6:00 p.m.'), ('19:00', '7:00 p.m.'), ('20:00', '8:00 p.m.')], verbose_name='Delivery Time'),
        ),
    ]
