# Generated by Django 3.2.9 on 2021-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(choices=[('9:00 a.m.', '9:00 a.m.'), ('10:00 a.m.', '10:00 a.m.'), ('11:00 a.m.', '11:00 a.m.'), ('12:00 p.m.', '12:00 p.m.'), ('1:00 p.m.', '1:00 p.m.'), ('2:00 p.m.', '2:00 p.m.'), ('3:00 p.m.', '3:00 p.m.'), ('4:00 p.m.', '4:00 p.m.'), ('5:00 p.m.', '5:00 p.m.'), ('6:00 p.m.', '6:00 p.m.'), ('7:00 p.m.', '7:00 p.m.'), ('8:00 p.m.', '8:00 p.m.')], max_length=10, verbose_name='Delivery Time'),
        ),
    ]
