# Generated by Django 3.2.9 on 2021-12-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(default='images/500_500.png', upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
