# Generated by Django 3.2.9 on 2021-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
