# Generated by Django 3.2.9 on 2021-12-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_reviewrating_review'),
        ('accounts', '0007_alter_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='services.service'),
        ),
    ]
