# Generated by Django 3.2.9 on 2021-12-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211223_0541'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE accounts_staff_id_seq RESTART WITH 1001;'
        )
    ]
