# Generated by Django 3.2.9 on 2021-12-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staffbookeddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbookeddatetime',
            name='time',
            field=models.CharField(blank=True, choices=[('9:00 a.m.', '9:00 a.m.'), ('10:00 a.m.', '10:00 a.m.'), ('11:00 a.m.', '11:00 a.m.'), ('12:00 p.m.', '12:00 p.m.'), ('1:00 p.m.', '1:00 p.m.'), ('2:00 p.m.', '2:00 p.m.'), ('3:00 p.m.', '3:00 p.m.'), ('4:00 p.m.', '4:00 p.m.'), ('5:00 p.m.', '5:00 p.m.'), ('6:00 p.m.', '6:00 p.m.'), ('7:00 p.m.', '7:00 p.m.'), ('8:00 p.m.', '8:00 p.m.')], max_length=10),
        ),
    ]
