# Generated by Django 3.2.9 on 2021-12-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211224_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbookeddatetime',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
    ]
