# Generated by Django 3.2.9 on 2021-12-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_staffbookeddatetime_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffbookeddatetime',
            options={'ordering': ['date']},
        ),
    ]
