# Generated by Django 3.2.9 on 2021-12-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_staffbookeddatetime_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='booked_on',
            field=models.ManyToManyField(related_name='booked_on', to='accounts.StaffBookedDateTime'),
        ),
    ]
