# Generated by Django 3.2.9 on 2021-12-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='images/500_500.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='image',
            field=models.ImageField(default='images/500_500.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Service Option Visibility'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Service Option Name'),
        ),
    ]
