# Generated by Django 3.2.9 on 2021-12-18 14:42

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211214_0336'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='serviceoption',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['name'], name='NewGinIndex', opclasses=['gin_trgm_ops']),
        ),
    ]
