# Generated by Django 3.2.9 on 2021-12-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceoption_newginindex'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceoption',
            name='NewGinIndex',
        ),
    ]
