# Generated by Django 3.2.9 on 2021-12-18 15:08

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_serviceoption_newginindex'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serviceoption',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='NewGinIndex', opclasses=['gin_trgm_ops']),
        ),
    ]
