# Generated by Django 3.2.9 on 2021-12-18 15:12

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceoption_newginindex'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='GinIndex', opclasses=['gin_trgm_ops']),
        ),
    ]
