# Generated by Django 3.2.9 on 2021-12-21 12:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_ginindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoption',
            name='notes',
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='pricing',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
