# Generated by Django 3.2.9 on 2021-12-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20211221_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='service_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.serviceoption'),
        ),
    ]
