# Generated by Django 3.2.9 on 2021-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_reviewrating_service_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='service_option',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='service_option',
            field=models.ManyToManyField(null=True, to='services.ServiceOption', verbose_name='Review for'),
        ),
    ]
