# Generated by Django 3.2.9 on 2021-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20211222_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=255, verbose_name='Review Details'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='service_option',
            field=models.ManyToManyField(to='services.ServiceOption', verbose_name='Review for'),
        ),
    ]
