# Generated by Django 3.2.9 on 2021-12-22 13:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20211222_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, verbose_name='Review Details'),
        ),
    ]
