# Generated by Django 3.2.9 on 2021-12-22 16:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_reviewrating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Review Details'),
        ),
    ]
